version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=msgr
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - my-network

  spring:
    image: alisk81/chatkon-backend:latest
    container_name: spring
    ports:
      - "8080:8080"
      - "5173:5173"
    depends_on:
      - mysql
    networks:
      - my-network

volumes:
  mysqldata:

networks:
  my-network:
    driver: bridge